# Generated by Django 4.0.5 on 2022-09-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_cover_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
